name: Build Next js web application
on: push
jobs:
  build:
  name: Build project
  runs-on: ubuntu-latest
  stpes:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Install npm dependencies
   run: npm install
   -name: Build project assets
   run: npm run build
  
      
